spring:
  profiles:
    active: dev
  application:
    name: simpleweb
  mvc:
    view:
      prefix: /
      suffix: .html
server:
  port: 8080
  #servlet:
  #  context-path: /ms
  
management:
  server:
    port: 9090

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.ms: DEBUG
    
---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2 
  datasource:
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
   # driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
        ddl-auto: create-drop
logging:
  level:
    root: ERROR
    com.spring.microservices: DEBUG


---
spring:
  profiles: qa
greeting: Hello from QA.