spring:
  profiles:
    active: dev
  application:
    name: simpleweb
  mvc:
    view:
      prefix: /
      suffix: .html
server:
  port: 8080
  #servlet:
  #  context-path: /ms
  
management:
  server:
    port: 9090

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.ms: DEBUG

---
spring:
  profiles: qa
greeting: Hello from QA.