server:
  port: 8888
spring:

  profiles:
    active: vault, git
  application:
    name: configserver
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      